### PR TITLE
chore(release): 2.0.0

### PR DESCRIPTION
**Pull request by scurker**
### ⚠ BREAKING CHANGES

- This functionality depends on newer versions of puppeteer (> 5.1.0)

### Features

- add ability to get an extension's content script execution context ([#31](https://github.com/dequelabs/puppeteer-devtools/issues/31)) ([8147349](https://github.com/dequelabs/puppeteer-devtools/commit/81473491ffb2f79b44720ea427cf08ff483b94b5))
- set minimum node version to 12 ([#28](https://github.com/dequelabs/puppeteer-devtools/issues/28)) ([d93df4f](https://github.com/dequelabs/puppeteer-devtools/commit/d93df4f83912773a1e95b46b9dc0bf98ddd534cf))

### CODE REVIEW

**Review by stephenmathieson — APPROVED** [review]
LGTM!

Do we need @erik-deque to sign off on the release, or is my approval sufficient?

**Comment by scurker** [comment]
I think @erik-deque may need to sign off and do a release audit.

**Review by erik-deque — APPROVED** [review]
lgtm

**Comment by erik-deque** [comment]
# Release Audit 
- [x] #29 
- [ ] #28 
- [ ] #32

**Pull request merged**
