### PR TITLE
chore: rename CODE_OF_CONDUCT.md to code_of_conduct.md

### PR DESCRIPTION
**Pull request by scurker**

### CODE REVIEW

**Comment by stephenmathieson** [comment]
🥜🦕

**Comment by tbusillo** [comment]
Verified with Voiceover and NVDA.

**Review by tbusillo — APPROVED** [review]

**Comment by stephenmathieson** [comment]
There's no difference. Why are we doing this?

**Comment by tbusillo** [comment]
@stephenmathieson From what I could tell from the conversations on slack and testing with VO/NVDA, it did make a difference with how it was announced via VO (NVDA handled it fine either way).

**Comment by stephenmathieson** [comment]
No, VO handles this fine. Refer to the Slack thread in #development.

**Comment by tbusillo** [comment]
I read the thread and maybe we are reading it differently/I am misunderstanding the conclusion, but [Abbey's comment](https://deque.slack.com/archives/CB3DV1QCW/p1664207821446079?thread_ts=1664206278.105129&cid=CB3DV1QCW) mentions that VO announces "CODE_OF_CONDUCT" as "CODE_OH EFF_CONDUCT", whereas "code_of_conduct" is pronounced properly. Also tested it in VO myself and confirmed this was the case. 

My takeaway from that conversation was that everyone was in agreement that lowercase _is_ more appropriate, but that the time investment might not be worthwhile. Since this is already done, don't see any reason to block it, imo.

**Pull request merged**
